/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

import UI_mapEleLvArr from "./UI_mapEleLvArr";

export default class UI_map extends fgui.GComponent {

	public m_c1:fgui.Controller;
	public m_n10:fgui.GImage;
	public m_map1:UI_mapEleLvArr;
	public m_map2:UI_mapEleLvArr;
	public m_map3:UI_mapEleLvArr;
	public m_map4:UI_mapEleLvArr;
	public m_map5:UI_mapEleLvArr;
	public m_map6:UI_mapEleLvArr;
	public m_map7:UI_mapEleLvArr;
	public m_map8:UI_mapEleLvArr;
	public m_map9:UI_mapEleLvArr;
	public m_map10:UI_mapEleLvArr;
	public m_n11:fgui.GGroup;
	public m_n23:fgui.GImage;
	public m_map11:UI_mapEleLvArr;
	public m_map12:UI_mapEleLvArr;
	public m_map13:UI_mapEleLvArr;
	public m_map14:UI_mapEleLvArr;
	public m_map15:UI_mapEleLvArr;
	public m_map16:UI_mapEleLvArr;
	public m_map17:UI_mapEleLvArr;
	public m_map18:UI_mapEleLvArr;
	public m_map19:UI_mapEleLvArr;
	public m_map20:UI_mapEleLvArr;
	public m_n24:fgui.GGroup;
	public m_n25:fgui.GImage;
	public m_map21:UI_mapEleLvArr;
	public m_map22:UI_mapEleLvArr;
	public m_map23:UI_mapEleLvArr;
	public m_map24:UI_mapEleLvArr;
	public m_map25:UI_mapEleLvArr;
	public m_map26:UI_mapEleLvArr;
	public m_map27:UI_mapEleLvArr;
	public m_map28:UI_mapEleLvArr;
	public m_map29:UI_mapEleLvArr;
	public m_map30:UI_mapEleLvArr;
	public m_n36:fgui.GGroup;
	public m_n37:fgui.GImage;
	public m_map31:UI_mapEleLvArr;
	public m_map32:UI_mapEleLvArr;
	public m_map33:UI_mapEleLvArr;
	public m_map34:UI_mapEleLvArr;
	public m_map35:UI_mapEleLvArr;
	public m_map36:UI_mapEleLvArr;
	public m_map37:UI_mapEleLvArr;
	public m_map38:UI_mapEleLvArr;
	public m_map39:UI_mapEleLvArr;
	public m_map40:UI_mapEleLvArr;
	public m_n49:fgui.GGroup;
	public m_n50:fgui.GImage;
	public m_map41:UI_mapEleLvArr;
	public m_map42:UI_mapEleLvArr;
	public m_map43:UI_mapEleLvArr;
	public m_map44:UI_mapEleLvArr;
	public m_map45:UI_mapEleLvArr;
	public m_map46:UI_mapEleLvArr;
	public m_map47:UI_mapEleLvArr;
	public m_map48:UI_mapEleLvArr;
	public m_map49:UI_mapEleLvArr;
	public m_map50:UI_mapEleLvArr;
	public m_n61:fgui.GGroup;
	public m_liftBtn:fgui.GImage;
	public m_rightBtn:fgui.GImage;
	public static URL:string = "ui://a4fmegqmzki02c";

	public static createInstance():UI_map {
		return <UI_map>(fgui.UIPackage.createObject("main", "map"));
	}

	protected onConstruct():void {
		this.m_c1 = this.getController("c1");
		this.m_n10 = <fgui.GImage>(this.getChild("n10"));
		this.m_map1 = <UI_mapEleLvArr>(this.getChild("map1"));
		this.m_map2 = <UI_mapEleLvArr>(this.getChild("map2"));
		this.m_map3 = <UI_mapEleLvArr>(this.getChild("map3"));
		this.m_map4 = <UI_mapEleLvArr>(this.getChild("map4"));
		this.m_map5 = <UI_mapEleLvArr>(this.getChild("map5"));
		this.m_map6 = <UI_mapEleLvArr>(this.getChild("map6"));
		this.m_map7 = <UI_mapEleLvArr>(this.getChild("map7"));
		this.m_map8 = <UI_mapEleLvArr>(this.getChild("map8"));
		this.m_map9 = <UI_mapEleLvArr>(this.getChild("map9"));
		this.m_map10 = <UI_mapEleLvArr>(this.getChild("map10"));
		this.m_n11 = <fgui.GGroup>(this.getChild("n11"));
		this.m_n23 = <fgui.GImage>(this.getChild("n23"));
		this.m_map11 = <UI_mapEleLvArr>(this.getChild("map11"));
		this.m_map12 = <UI_mapEleLvArr>(this.getChild("map12"));
		this.m_map13 = <UI_mapEleLvArr>(this.getChild("map13"));
		this.m_map14 = <UI_mapEleLvArr>(this.getChild("map14"));
		this.m_map15 = <UI_mapEleLvArr>(this.getChild("map15"));
		this.m_map16 = <UI_mapEleLvArr>(this.getChild("map16"));
		this.m_map17 = <UI_mapEleLvArr>(this.getChild("map17"));
		this.m_map18 = <UI_mapEleLvArr>(this.getChild("map18"));
		this.m_map19 = <UI_mapEleLvArr>(this.getChild("map19"));
		this.m_map20 = <UI_mapEleLvArr>(this.getChild("map20"));
		this.m_n24 = <fgui.GGroup>(this.getChild("n24"));
		this.m_n25 = <fgui.GImage>(this.getChild("n25"));
		this.m_map21 = <UI_mapEleLvArr>(this.getChild("map21"));
		this.m_map22 = <UI_mapEleLvArr>(this.getChild("map22"));
		this.m_map23 = <UI_mapEleLvArr>(this.getChild("map23"));
		this.m_map24 = <UI_mapEleLvArr>(this.getChild("map24"));
		this.m_map25 = <UI_mapEleLvArr>(this.getChild("map25"));
		this.m_map26 = <UI_mapEleLvArr>(this.getChild("map26"));
		this.m_map27 = <UI_mapEleLvArr>(this.getChild("map27"));
		this.m_map28 = <UI_mapEleLvArr>(this.getChild("map28"));
		this.m_map29 = <UI_mapEleLvArr>(this.getChild("map29"));
		this.m_map30 = <UI_mapEleLvArr>(this.getChild("map30"));
		this.m_n36 = <fgui.GGroup>(this.getChild("n36"));
		this.m_n37 = <fgui.GImage>(this.getChild("n37"));
		this.m_map31 = <UI_mapEleLvArr>(this.getChild("map31"));
		this.m_map32 = <UI_mapEleLvArr>(this.getChild("map32"));
		this.m_map33 = <UI_mapEleLvArr>(this.getChild("map33"));
		this.m_map34 = <UI_mapEleLvArr>(this.getChild("map34"));
		this.m_map35 = <UI_mapEleLvArr>(this.getChild("map35"));
		this.m_map36 = <UI_mapEleLvArr>(this.getChild("map36"));
		this.m_map37 = <UI_mapEleLvArr>(this.getChild("map37"));
		this.m_map38 = <UI_mapEleLvArr>(this.getChild("map38"));
		this.m_map39 = <UI_mapEleLvArr>(this.getChild("map39"));
		this.m_map40 = <UI_mapEleLvArr>(this.getChild("map40"));
		this.m_n49 = <fgui.GGroup>(this.getChild("n49"));
		this.m_n50 = <fgui.GImage>(this.getChild("n50"));
		this.m_map41 = <UI_mapEleLvArr>(this.getChild("map41"));
		this.m_map42 = <UI_mapEleLvArr>(this.getChild("map42"));
		this.m_map43 = <UI_mapEleLvArr>(this.getChild("map43"));
		this.m_map44 = <UI_mapEleLvArr>(this.getChild("map44"));
		this.m_map45 = <UI_mapEleLvArr>(this.getChild("map45"));
		this.m_map46 = <UI_mapEleLvArr>(this.getChild("map46"));
		this.m_map47 = <UI_mapEleLvArr>(this.getChild("map47"));
		this.m_map48 = <UI_mapEleLvArr>(this.getChild("map48"));
		this.m_map49 = <UI_mapEleLvArr>(this.getChild("map49"));
		this.m_map50 = <UI_mapEleLvArr>(this.getChild("map50"));
		this.m_n61 = <fgui.GGroup>(this.getChild("n61"));
		this.m_liftBtn = <fgui.GImage>(this.getChild("liftBtn"));
		this.m_rightBtn = <fgui.GImage>(this.getChild("rightBtn"));
	}
}